name: allegro_pdf
description: "Pdf reader optimized for music sheets"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  flex_color_picker: ^3.3.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.1
  infinite_scroll_pagination: ^4.0.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true